export const CSS = String.raw`
.skk-global-enabled .pI_x6G_centerCol,.skk-global-enabled [data-slot="conversation"]>*{background-image:linear-gradient(rgba(3,7,27,.38),rgba(3,5,22,.72)),var(--skk-global-background)!important;background-size:100vw 100vh!important;background-position:center center!important;background-repeat:no-repeat!important}.skk-global-enabled .pI_x6G_centerCol{background-color:#050819!important;transform:translateZ(0);backface-visibility:hidden}.skk-global-enabled [data-slot="sidebar"]>div{background-image:linear-gradient(rgba(3,7,25,.2),rgba(3,6,24,.34)),var(--skk-global-sidebar)!important;background-size:cover!important;background-position:center!important}
.skk-sidebar-resizer{position:fixed;top:0;width:7px;z-index:9999;cursor:col-resize;background:linear-gradient(90deg,transparent,rgba(105,220,255,.42),transparent);opacity:.42;transition:opacity .16s ease,background .16s ease;display:none;will-change:left,opacity;transform:translateZ(0)}.skk-sidebar-resizer:hover,body.skk-sidebar-dragging .skk-sidebar-resizer{opacity:1;background:linear-gradient(90deg,transparent,rgba(105,220,255,.78),transparent);box-shadow:0 0 18px rgba(105,220,255,.28)}body.skk-sidebar-dragging{cursor:col-resize;user-select:none}body.skk-sidebar-dragging iframe,body.skk-sidebar-dragging [data-slot="conversation"]{pointer-events:none}
body.skk-sidebar-dragging .pI_x6G_centerCol,body.skk-sidebar-dragging [data-slot="conversation"]>*{background-size:100vw 100vh!important;background-attachment:local!important}
.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)){position:relative;isolation:isolate;overflow:auto;background:#050819!important}
.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root))::before{content:"";position:absolute;inset:0;z-index:0;background:radial-gradient(circle at 62% 38%,rgba(111,222,255,.1),transparent 0 28%,rgba(3,5,20,.76) 74%),linear-gradient(90deg,rgba(3,6,22,.68),rgba(4,8,30,.16) 48%,rgba(3,4,16,.42)),var(--skk-newchat-background);background-size:100vw 100vh;background-position:center;filter:saturate(1.08) brightness(.9);transform:scale(1.018) translateZ(0);will-change:transform}
.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root))>*{position:relative;z-index:2}
.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) .wSkVaW_root,.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) [data-conversation-scroll]{background:transparent!important}
.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) [data-conversation-scroll]{position:relative!important;isolation:isolate;overflow:auto!important}
.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) [data-conversation-scroll]>*{position:relative;z-index:3}
.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) [data-conversation-scroll]::before{content:"ABYSS · SKIRK THEATER";position:absolute;left:clamp(28px,4vw,72px);top:clamp(28px,5vh,70px);z-index:2;color:#d6f4ff;font-size:12px;letter-spacing:.22em;text-shadow:0 0 14px rgba(103,217,255,.78);pointer-events:none}
.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) [data-slot="conversation.composer"]{position:relative;z-index:5}
.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) [data-slot="conversation.composer"] .wSkVaW_heroGlow{display:none!important}
.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) [data-slot="conversation.composer"] .pXSMma_root{color:#f5f8ff!important;text-shadow:0 0 18px rgba(103,217,255,.45)}
.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) [data-slot="conversation.composer"] .pXSMma_root::before{content:none!important;display:none!important}
.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) [data-slot="conversation.composer"] [data-slot="conversation.composer.bar"]>div{border:0!important;border-radius:0!important;background:transparent!important;box-shadow:none!important;backdrop-filter:none!important}
.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) [data-slot="conversation.composer"] .uV2eYG_card{border:1px solid rgba(112,214,255,.68)!important;border-radius:16px!important;background:linear-gradient(120deg,rgba(3,8,30,.9),rgba(10,17,46,.78))!important;box-shadow:0 18px 60px rgba(0,0,20,.52),inset 0 0 34px rgba(76,110,255,.08)!important;backdrop-filter:blur(14px)}
.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) [data-slot="conversation.composer"] .uV2eYG_scroll,.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) [data-slot="conversation.composer"] .uV2eYG_grow,.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) [data-slot="conversation.composer"] .uV2eYG_row{background:transparent!important}
.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) [data-slot="conversation.composer"] textarea{color:#f5f8ff!important;background:transparent!important}
.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) [data-slot="conversation.composer"] textarea::placeholder{color:#bdd2eb!important}
.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) [data-slot="conversation.composer"] button,.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) [data-slot="conversation.composer"] [role="button"]{color:#9deeff!important}
.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) [data-slot="conversation.composer"] button svg,.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) [data-slot="conversation.composer"] [role="button"] svg{color:#9deeff!important;stroke:currentColor!important}
.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) [data-slot="conversation.composer"] button[aria-label="发送消息"]{border:1px solid rgba(112,220,255,.52)!important;background:linear-gradient(135deg,rgba(64,28,136,.85),rgba(28,112,169,.85))!important;color:#fff!important;box-shadow:0 0 18px rgba(104,214,255,.18)}
.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) [data-slot="conversation.composer"] button[aria-label="选择工作区"],.skk-global-enabled [data-slot="conversation"]:not(:has(.skk-root)) [data-slot="conversation.composer"] button[aria-label="命令"]{border-color:rgba(112,214,255,.28)!important;color:#9deeff!important}
:root { --skk-blue:#67d9ff; --skk-violet:#8b6cff; --skk-ink:#070b21; }
.skk-root,.skk-root *{box-sizing:border-box}
.skk-root{position:relative;width:100%;height:100%;min-height:560px;overflow:hidden;color:#f7f8ff;font-family:"Segoe UI","Microsoft YaHei",sans-serif;background:#070b21;isolation:isolate}
.skk-bg{position:absolute;inset:-3%;background-size:cover;background-position:center;filter:saturate(1.12) brightness(.82);animation:skk-camera 18s ease-in-out infinite alternate;z-index:-4}
.skk-vignette{position:absolute;inset:0;background:radial-gradient(circle at 62% 38%,transparent 0 18%,rgba(4,5,24,.2) 56%,rgba(2,3,14,.82) 100%),linear-gradient(90deg,rgba(3,5,20,.52),transparent 38%);z-index:-2;pointer-events:none}
.skk-stars{position:absolute;inset:0;z-index:-1;pointer-events:none;background-image:radial-gradient(circle,#bff4ff 0 1px,transparent 1.5px),radial-gradient(circle,#a48aff 0 1px,transparent 1.4px);background-size:83px 83px,127px 127px;background-position:17px 31px,51px 12px;opacity:.34;animation:skk-stars 10s linear infinite}
.skk-character{position:absolute;right:clamp(12px,2.5vw,46px);bottom:clamp(156px,20vh,184px);width:min(40vw,580px);height:calc(100% - 84px);display:flex;align-items:flex-end;justify-content:flex-end;pointer-events:none;transform-origin:48% 60%;animation:skk-breathe 6.4s ease-in-out infinite}
.skk-character img{display:block;max-width:100%;max-height:100%;object-fit:contain;object-position:right bottom;filter:drop-shadow(0 15px 28px rgba(7,3,38,.75)) drop-shadow(0 0 18px rgba(84,202,255,.16));transform-origin:44% 42%;animation:skk-silhouette 7.2s ease-in-out infinite}
.skk-aura{position:absolute;right:16%;bottom:30%;width:38%;aspect-ratio:1;border-radius:50%;background:radial-gradient(circle,rgba(91,223,255,.23),rgba(112,77,255,.09) 43%,transparent 70%);filter:blur(18px);mix-blend-mode:screen;animation:skk-aura 4.8s ease-in-out infinite;z-index:-1}
.skk-topbar{position:absolute;left:24px;right:24px;top:20px;display:flex;align-items:center;justify-content:space-between;z-index:5}
.skk-title{letter-spacing:.2em;font-size:12px;color:#c7eefe;text-shadow:0 0 12px rgba(94,217,255,.8)}
.skk-chip,.skk-icon{border:1px solid rgba(134,220,255,.32);background:rgba(6,11,34,.54);color:#eefaff;border-radius:999px;backdrop-filter:blur(12px);cursor:pointer;transition:.2s ease}
.skk-chip{padding:8px 15px}.skk-chip:hover,.skk-icon:hover{border-color:#69dcff;background:rgba(40,65,124,.58)}
.skk-response-zone{position:absolute;left:clamp(24px,4vw,72px);top:84px;bottom:150px;width:min(48vw,780px);display:flex;flex-direction:column;border:1px solid rgba(112,214,255,.3);border-radius:16px;background:linear-gradient(135deg,rgba(3,8,30,.62),rgba(14,11,52,.38));box-shadow:0 18px 60px rgba(0,0,20,.28),inset 0 0 45px rgba(82,102,255,.05);backdrop-filter:blur(9px);z-index:3;overflow:hidden}
.skk-response-head{height:45px;flex:0 0 auto;display:flex;align-items:center;justify-content:space-between;padding:0 14px 0 18px;border-bottom:1px solid rgba(121,206,255,.2);color:#c7efff;font-size:12px;letter-spacing:.13em;text-transform:uppercase}.skk-response-tools{display:flex;gap:7px}.skk-response-feed{flex:1;min-height:0;padding:14px 16px 22px;overflow:auto;scrollbar-width:thin;scrollbar-color:rgba(104,220,255,.36) transparent}.skk-response-card{position:relative;margin:0 0 12px;padding:13px 16px 14px;border:1px solid rgba(125,202,255,.22);border-left:2px solid #6bdfff;border-radius:4px 12px 12px 4px;background:linear-gradient(105deg,rgba(5,11,38,.88),rgba(27,20,73,.62));box-shadow:0 9px 25px rgba(1,2,18,.24)}.skk-response-card:last-child{border-color:rgba(110,222,255,.48);box-shadow:0 0 26px rgba(69,161,255,.1)}.skk-response-card.is-status{border-left-color:#9e87ff}.skk-response-meta{display:flex;align-items:center;justify-content:space-between;margin-bottom:7px;color:#7de2ff;font-size:11px;letter-spacing:.1em}.skk-response-meta strong{font-size:13px}.skk-response-meta span{color:#7787ac;font-size:9px}.skk-response-card p{margin:0;color:#f2f5ff;font-size:clamp(13px,.9vw,16px);line-height:1.65;white-space:pre-wrap;text-shadow:0 2px 7px rgba(0,0,0,.55)}
.skk-userbox{position:absolute;left:clamp(18px,3vw,54px);right:clamp(18px,3vw,54px);bottom:clamp(14px,2vh,26px);height:105px;padding:29px 22px 13px;border:1px solid rgba(112,214,255,.68);border-radius:15px;background:linear-gradient(120deg,rgba(4,10,34,.91),rgba(16,15,60,.8));box-shadow:0 18px 60px rgba(0,0,20,.58),inset 0 0 34px rgba(76,110,255,.08);backdrop-filter:blur(16px);z-index:4}.skk-userbox:before{content:"";position:absolute;inset:5px;border:1px solid rgba(129,100,255,.2);border-radius:13px;pointer-events:none}.skk-user-last{position:absolute;left:214px;right:22px;top:8px;margin:0;color:#aebbd5;font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.skk-userbox .skk-composer{left:22px;right:22px;bottom:13px}.skk-userbox .skk-input{height:37px;font-size:13px}.skk-userbox .skk-send{width:46px}
.skk-dialogue{position:absolute;left:clamp(18px,3vw,54px);right:clamp(18px,3vw,54px);bottom:clamp(14px,2vh,26px);height:158px;min-height:0;padding:32px 26px 48px;border:1px solid rgba(112,214,255,.68);border-radius:15px;background:linear-gradient(120deg,rgba(4,10,34,.88),rgba(16,15,60,.76));box-shadow:0 18px 60px rgba(0,0,20,.58),inset 0 0 34px rgba(76,110,255,.08);backdrop-filter:blur(16px);z-index:4}
.skk-dialogue:before{content:"";position:absolute;inset:5px;border:1px solid rgba(129,100,255,.2);border-radius:13px;pointer-events:none}
.skk-name{position:absolute;left:22px;top:-24px;min-width:174px;padding:8px 28px;border:1px solid rgba(125,227,255,.8);border-radius:12px 12px 4px 4px;background:linear-gradient(100deg,rgba(64,28,136,.96),rgba(18,122,176,.96));font-size:18px;font-weight:700;text-align:center;letter-spacing:.12em;box-shadow:0 8px 25px rgba(15,8,65,.5)}
.skk-name[data-role="player"]{background:linear-gradient(100deg,rgba(16,75,120,.96),rgba(35,104,151,.96))}.skk-name[data-role="system"]{background:#303854}
.skk-text{position:relative;margin:0;max-width:min(1040px,76vw);height:58px;overflow:auto;font-size:clamp(14px,1.05vw,18px);line-height:1.55;white-space:pre-wrap;text-shadow:0 2px 8px rgba(0,0,0,.7);scrollbar-width:thin;scrollbar-color:rgba(105,220,255,.35) transparent}
.skk-status{color:#9deeff}.skk-caret{display:inline-block;width:8px;height:1.05em;margin-left:5px;vertical-align:-.12em;background:#89e8ff;animation:skk-blink .8s steps(1) infinite}
.skk-actions{position:absolute;right:18px;bottom:10px;display:flex;gap:7px}.skk-action{min-width:70px;height:30px;padding:0 10px;border:1px solid rgba(124,214,255,.34);border-radius:7px;background:rgba(6,10,32,.62);color:#e8f8ff;font-size:11px;letter-spacing:.04em;cursor:pointer}.skk-action:hover,.skk-action.is-on{border-color:#71e1ff;background:linear-gradient(90deg,rgba(53,76,166,.8),rgba(62,30,136,.75))}
.skk-composer{position:absolute;left:24px;right:356px;bottom:10px;display:flex;gap:7px}.skk-input{width:100%;height:30px;padding:5px 12px;border:1px solid rgba(123,205,255,.25);border-radius:7px;background:rgba(2,7,28,.6);color:white;font-size:12px;outline:none}.skk-input:focus{border-color:#6edfff}.skk-send{width:38px;border:1px solid rgba(112,220,255,.5);border-radius:7px;background:rgba(62,88,180,.54);color:white;cursor:pointer}.skk-permission{position:relative;flex:0 0 auto}.skk-permission-button{height:37px;min-width:146px;display:flex;align-items:center;justify-content:center;gap:7px;padding:0 12px;border:1px solid rgba(123,205,255,.34);border-radius:8px;background:linear-gradient(135deg,rgba(7,18,47,.82),rgba(35,42,96,.58));color:#dff8ff;font-weight:700;cursor:pointer;box-shadow:inset 0 0 18px rgba(103,217,255,.06)}.skk-permission-button:hover{border-color:rgba(112,220,255,.72);box-shadow:0 0 14px rgba(104,214,255,.16)}.skk-permission-button:disabled{opacity:.68;cursor:wait}.skk-permission-icon{color:#8eefff;text-shadow:0 0 9px rgba(112,220,255,.8)}.skk-permission-button i{font-style:normal;color:#9bb7d7}.skk-permission-menu{position:absolute;left:0;bottom:calc(100% + 9px);width:270px;padding:8px;border:1px solid rgba(112,220,255,.38);border-radius:13px;background:linear-gradient(135deg,rgba(21,26,50,.98),rgba(40,42,66,.96));box-shadow:0 18px 50px rgba(0,0,0,.46),inset 0 0 28px rgba(91,215,255,.06);backdrop-filter:blur(18px);z-index:30}.skk-permission-menu button{width:100%;min-height:42px;display:grid;grid-template-columns:24px minmax(0,1fr) 20px;align-items:center;gap:9px;padding:7px 9px;border:0;border-radius:9px;background:transparent;color:#f2f7ff;text-align:left;cursor:pointer}.skk-permission-menu button:hover,.skk-permission-menu button[aria-selected="true"]{background:rgba(112,220,255,.12)}.skk-permission-menu strong{display:block;font-size:13px}.skk-permission-menu small{display:block;margin-top:2px;color:#9eb0ca;font-size:10px;line-height:1.25}.skk-permission-menu em{font-style:normal;color:#fff;font-size:16px}.skk-permission-menu p{margin:6px 8px 2px;color:#ff9b9b;font-size:11px}
.skk-panel{position:absolute;top:0;right:0;width:min(440px,92vw);height:100%;padding:24px;background:rgba(5,8,27,.95);border-left:1px solid rgba(109,214,255,.35);backdrop-filter:blur(20px);z-index:10;box-shadow:-20px 0 70px rgba(0,0,20,.5);overflow:auto}.skk-panel-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:22px;font-size:20px}.skk-history-row{padding:13px 0;border-bottom:1px solid rgba(143,202,255,.12)}.skk-history-name{display:block;color:#85e6ff;font-weight:700;margin-bottom:6px}.skk-history-text{margin:0;color:#dfe7fa;white-space:pre-wrap;line-height:1.6}.skk-setting{display:grid;gap:7px;margin:18px 0;color:#dbe8ff}.skk-setting input,.skk-setting select{padding:10px;border:1px solid rgba(135,210,255,.3);border-radius:8px;background:#0b1231;color:white}.skk-empty{color:#91a1c5}.skk-mobile-hint{display:none}
.skk-workflow{margin:0 0 12px;padding:12px 14px;border:1px solid rgba(102,217,255,.28);border-radius:10px;background:rgba(3,9,32,.78)}.skk-workflow>header{display:flex;justify-content:space-between;color:#8ee8ff;font-size:11px}.skk-workflow>p{margin:10px 0 0;color:#91a1c5;font-size:11px}.skk-workflow-item{display:grid;grid-template-columns:8px minmax(0,1fr) auto;gap:9px;align-items:start;padding:9px 0;border-top:1px solid rgba(117,196,255,.12)}.skk-workflow>header+.skk-workflow-item{margin-top:8px}.skk-workflow-item i{width:7px;height:7px;margin-top:5px;border-radius:50%;background:#69dfff;box-shadow:0 0 8px #69dfff}.skk-workflow-item.is-running i{animation:skk-blink .9s infinite}.skk-workflow-item strong{font-size:11px}.skk-workflow-item pre{max-height:100px;margin:4px 0 0;overflow:auto;white-space:pre-wrap;word-break:break-word;color:#aab7d1;font:10px/1.45 Consolas,monospace}.skk-workflow-item>span{color:#7f90ae;font-size:9px}.skk-pending-panel{position:absolute;left:clamp(24px,4vw,72px);right:clamp(18px,3vw,54px);bottom:132px;z-index:8;display:grid;gap:8px;max-height:min(34vh,300px);overflow:auto;padding:12px;border:1px solid rgba(255,197,88,.56);border-radius:14px;background:linear-gradient(120deg,rgba(20,17,44,.96),rgba(10,26,55,.9));box-shadow:0 14px 44px rgba(0,0,0,.42),inset 0 0 24px rgba(255,214,122,.08);backdrop-filter:blur(16px);scrollbar-width:thin}.skk-pending-panel>header{display:flex;align-items:center;justify-content:space-between;color:#ffd98a;font-size:12px;letter-spacing:.08em}.skk-pending-panel>header span{color:#b9c5df;font-size:10px}.skk-pending-card{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:10px 12px;border:1px solid rgba(124,214,255,.24);border-radius:11px;background:rgba(3,8,30,.65)}.skk-pending-copy{display:grid;gap:4px;min-width:0}.skk-pending-copy strong{color:#ffd98a;font-size:13px}.skk-pending-copy span{font-size:11px;color:#e7e9f7}.skk-pending-copy code{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#9fcaff;font-size:10px}.skk-pending-copy em{color:#ff9b9b;font-size:10px}.skk-pending-questions{display:grid;gap:6px;margin-top:4px}.skk-pending-questions label{display:grid;grid-template-columns:minmax(90px,160px) minmax(160px,1fr);align-items:center;gap:8px;color:#dceaff;font-size:11px}.skk-pending-questions input,.skk-pending-questions select{min-width:0;height:28px;padding:4px 8px;border:1px solid rgba(124,214,255,.3);border-radius:7px;background:#091133;color:#eefaff}.skk-pending-actions{display:flex;gap:8px;flex:none}.skk-pending-actions button{padding:7px 13px;border:1px solid rgba(255,255,255,.2);border-radius:7px;background:#151c3e;color:#e8edff;cursor:pointer}.skk-pending-actions button.is-allow{border-color:rgba(102,220,255,.5);background:#22518c}.skk-pending-actions button:disabled{opacity:.55;cursor:wait}
.skk-quick-settings{display:grid;grid-template-columns:1fr 1fr;gap:18px 24px;width:min(820px,100%);padding:4px 2px 28px;color:inherit}.skk-quick-intro{grid-column:1/-1;display:flex;align-items:center;justify-content:space-between;padding:18px 20px;border:1px solid rgba(103,217,255,.25);border-radius:14px;background:linear-gradient(105deg,rgba(30,34,82,.5),rgba(20,68,102,.25))}.skk-quick-intro strong{font-size:18px}.skk-quick-intro p{margin:5px 0 0;color:#9aa8c2}.skk-quick-intro button{padding:9px 16px;border:1px solid rgba(103,217,255,.55);border-radius:999px;background:#17274d;color:#eefaff;cursor:pointer}.skk-quick-settings label{display:grid;gap:8px;color:#dbe8ff}.skk-quick-toggle{grid-column:1/-1;padding:14px 16px;border:1px solid rgba(103,217,255,.22);border-radius:12px;background:rgba(8,16,42,.42)}.skk-quick-settings input,.skk-quick-settings select{height:42px;padding:8px 11px;border:1px solid rgba(123,205,255,.28);border-radius:9px;background:#0b1231;color:#fff}.skk-quick-note{grid-column:1/-1;margin:0;color:#8e9dbb;font-size:12px}
.skk-session-manager{grid-column:1/-1;margin-top:8px;padding-top:22px;border-top:1px solid rgba(123,205,255,.18)}.skk-manager-head{display:flex;align-items:center;justify-content:space-between;gap:16px}.skk-manager-head strong{font-size:17px}.skk-manager-head p{margin:5px 0 0;color:#93a2bf;font-size:12px}.skk-manager-head button,.skk-session-side button{padding:7px 13px;border:1px solid rgba(103,217,255,.35);border-radius:8px;background:#111b3b;color:#eafaff;cursor:pointer}.skk-storage-note{display:flex;flex-wrap:wrap;gap:8px 18px;margin:14px 0;padding:11px 13px;border-radius:9px;background:rgba(8,15,42,.62);color:#aebbd2;font-size:11px}.skk-storage-note span{display:flex;gap:5px}.skk-session-list{max-height:320px;overflow:auto;border:1px solid rgba(123,205,255,.18);border-radius:11px}.skk-session-row{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:12px 14px;border-bottom:1px solid rgba(123,205,255,.12)}.skk-session-row:last-child{border-bottom:0}.skk-session-row>div:first-child{display:grid;min-width:0;gap:3px}.skk-session-row strong{font-size:13px}.skk-session-row span,.skk-session-row code{color:#8d9bb6;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.skk-session-side{display:grid;justify-items:end;gap:7px;flex:0 0 auto}.skk-session-side time{color:#7f8da8;font-size:10px}.skk-archived,.skk-pending{padding:5px 9px;border-radius:999px;background:rgba(128,102,220,.2);color:#c7bcff!important}.skk-pending{background:rgba(69,174,214,.18);color:#8fe6ff!important}.skk-session-side button.skk-danger,.skk-trash button.skk-danger{border-color:rgba(255,112,130,.38);color:#ff9aaa}.skk-trash{margin-top:14px;display:grid;gap:8px}.skk-trash>strong{font-size:13px}.skk-trash-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px 12px;border:1px solid rgba(123,205,255,.14);border-radius:9px;background:rgba(7,13,38,.42)}.skk-trash-row>div:first-child{display:grid;gap:2px;min-width:0}.skk-trash-row span{font-size:12px}.skk-trash-row code,.skk-trash-row time{font-size:9px;color:#8290aa}.skk-trash-row>div:last-child{display:flex;gap:7px}.skk-trash-row button{padding:6px 10px;border:1px solid rgba(103,217,255,.35);border-radius:7px;background:#111b3b;color:#eafaff;cursor:pointer}.skk-manager-warning,.skk-manager-error,.skk-manager-empty{font-size:11px;line-height:1.55}.skk-manager-warning{color:#c9a8a8}.skk-manager-error{color:#ff9b9b}.skk-manager-empty{color:#8e9dbb}
@keyframes skk-camera{to{transform:scale(1.055) translate3d(-.8%,.4%,0)}}
@keyframes skk-stars{to{background-position:17px 114px,51px 139px}}
@keyframes skk-breathe{0%,100%{transform:translate3d(0,0,0) rotate(-.12deg)}50%{transform:translate3d(0,-8px,0) rotate(.16deg)}}
@keyframes skk-silhouette{0%,100%{transform:skewX(0deg) rotate(0deg)}38%{transform:skewX(-.32deg) rotate(-.16deg)}70%{transform:skewX(.2deg) rotate(.12deg)}}
@keyframes skk-aura{50%{transform:scale(1.16);opacity:.72}}@keyframes skk-blink{50%{opacity:0}}
@media(max-width:800px){.skk-root{min-height:520px}.skk-character{right:-10%;width:78vw;height:58%;bottom:118px;opacity:.48}.skk-response-zone{left:12px;right:12px;top:62px;bottom:126px;width:auto}.skk-response-head{padding-left:12px;font-size:10px}.skk-response-feed{padding:10px}.skk-response-card{padding:10px 12px}.skk-response-card p{font-size:13px}.skk-userbox{left:10px;right:10px;height:96px;padding:25px 12px 10px}.skk-userbox .skk-name{left:12px;min-width:132px;font-size:14px}.skk-user-last{left:156px;top:7px}.skk-userbox .skk-composer{left:12px;right:12px;bottom:10px}.skk-permission-button{min-width:42px;width:42px;padding:0}.skk-permission-button span:not(.skk-permission-icon),.skk-permission-button i{display:none}.skk-permission-menu{width:min(270px,calc(100vw - 28px))}.skk-action{min-width:0;padding:0 7px;font-size:9px}.skk-title{display:none}.skk-quick-settings{grid-template-columns:1fr}.skk-quick-intro,.skk-quick-note{grid-column:1}}
/* Host chrome theme, scoped to the active Skirk conversation view. */
body.skk-global-enabled [data-slot="sidebar"]>div,body.skk-host-active [data-slot="sidebar"]>div{background-color:#080c25!important;border-right:1px solid rgba(105,214,255,.34)!important;box-shadow:8px 0 36px rgba(3,4,22,.48),inset -1px 0 rgba(121,91,255,.2)}
body.skk-sidebar-collapsed [data-slot="sidebar"]>div{overflow:hidden!important;background-size:auto 100%!important;background-position:left center!important}
body.skk-sidebar-collapsed [data-slot="sidebar"] .hHd-Xa_brand,body.skk-sidebar-collapsed [data-slot="sidebar.workspaces"]{display:none!important}
body.skk-sidebar-collapsed [data-slot="sidebar"] button,body.skk-sidebar-collapsed [data-slot="sidebar"] [role="button"]{margin-left:0!important;margin-right:0!important}
body.skk-sidebar-collapsed [data-slot="sidebar"] .VOzbGW_rail{left:10px!important;right:auto!important}
body.skk-global-enabled [data-slot="sidebar"] button,body.skk-host-active [data-slot="sidebar"] button{border-color:rgba(105,214,255,.22)!important;color:#e9f8ff!important}
body.skk-global-enabled [data-slot="sidebar"] button:hover,body.skk-host-active [data-slot="sidebar"] button:hover{background:rgba(79,81,169,.28)!important;border-color:rgba(105,214,255,.55)!important}
body.skk-global-enabled [data-slot="sidebar"] .hHd-Xa_newSession{border:1px solid rgba(112,214,255,.5)!important;border-radius:14px!important;background:linear-gradient(100deg,rgba(18,38,84,.78),rgba(20,103,145,.58))!important;box-shadow:inset 0 0 18px rgba(105,214,255,.08),0 12px 26px rgba(0,0,22,.28)!important;color:#f4fbff!important}
body.skk-global-enabled [data-slot="sidebar"] .hHd-Xa_newSession:hover{background:linear-gradient(100deg,rgba(37,57,118,.86),rgba(27,129,172,.66))!important;box-shadow:inset 0 0 22px rgba(105,214,255,.14),0 0 22px rgba(105,214,255,.14)!important}
body.skk-global-enabled [data-slot="sidebar.workspaces"] .qDHVXG_sectionLabel{color:#bdefff!important;text-shadow:0 0 10px rgba(103,217,255,.34)}
body.skk-global-enabled [data-slot="sidebar.workspaces"] [role="treeitem"],body.skk-global-enabled [data-slot="sidebar.workspaces"] .YDXeBa_projectRow{position:relative!important;overflow:hidden!important;border:1px solid transparent!important;border-radius:12px!important;color:#eefaff!important;transition:background .16s ease,border-color .16s ease,box-shadow .16s ease}
body.skk-global-enabled [data-slot="sidebar.workspaces"] [role="treeitem"]:hover,body.skk-global-enabled [data-slot="sidebar.workspaces"] .YDXeBa_projectRow:hover{border-color:rgba(112,214,255,.28)!important;background:linear-gradient(90deg,rgba(42,57,128,.38),rgba(18,94,134,.25))!important}
body.skk-global-enabled [data-slot="sidebar.workspaces"] [role="treeitem"][aria-selected="true"],body.skk-global-enabled [data-slot="sidebar.workspaces"] [data-selected="true"],body.skk-global-enabled [data-slot="sidebar.workspaces"] [aria-current="page"],body.skk-host-active [data-slot="sidebar.workspaces"] [role="treeitem"][aria-selected="true"],body.skk-host-active [data-slot="sidebar.workspaces"] [data-selected="true"]{border-color:rgba(112,220,255,.7)!important;background:linear-gradient(90deg,rgba(67,63,154,.72),rgba(21,104,151,.62))!important;box-shadow:inset 3px 0 #70dcff,inset 0 0 24px rgba(109,77,255,.16),0 0 18px rgba(105,214,255,.1)!important;color:#fff!important}
body.skk-global-enabled [data-slot="sidebar.workspaces"] [role="treeitem"][aria-selected="true"]::before,body.skk-global-enabled [data-slot="sidebar.workspaces"] [data-selected="true"]::before,body.skk-global-enabled [data-slot="sidebar.workspaces"] [aria-current="page"]::before{content:"";position:absolute;left:0;top:9px;bottom:9px;width:3px;border-radius:99px;background:#70dcff;box-shadow:0 0 12px rgba(112,220,255,.85)}
body.skk-global-enabled [data-slot="sidebar.workspaces"] .YDXeBa_title,body.skk-global-enabled [data-slot="sidebar.workspaces"] .YDXeBa_projectText{color:#f3fbff!important;text-shadow:0 1px 4px rgba(0,0,16,.5)}
body.skk-global-enabled [data-slot="sidebar.workspaces"] time,body.skk-global-enabled [data-slot="sidebar.workspaces"] [class*="time"],body.skk-global-enabled [data-slot="sidebar.workspaces"] [class*="Time"]{color:#a9eaff!important}
body.skk-global-enabled [data-slot="sidebar.settings"]>button,body.skk-host-active [data-slot="sidebar.settings"]>button{background:rgba(30,36,82,.36)!important;border:1px solid rgba(111,210,255,.18)!important;border-radius:10px!important}
body.skk-global-enabled [data-slot="conversation.session.header"],body.skk-host-active [data-slot="conversation.session.header"]{background:linear-gradient(90deg,rgba(5,10,28,.96),rgba(10,22,48,.92) 52%,rgba(7,10,24,.96))!important;border-bottom:1px solid rgba(104,215,255,.28)!important;box-shadow:0 8px 26px rgba(2,4,24,.34),inset 0 -1px rgba(119,92,255,.16)!important;backdrop-filter:blur(14px)}
body.skk-global-enabled [data-slot="conversation.session.header"]::after,body.skk-host-active [data-slot="conversation.session.header"]::after{content:"";position:absolute;left:0;right:0;bottom:-1px;height:1px;background:linear-gradient(90deg,transparent,rgba(105,220,255,.54),rgba(139,108,255,.34),transparent);pointer-events:none}
body.skk-global-enabled [data-slot="conversation.session.header"] [role="tab"],body.skk-host-active [data-slot="conversation.session.header"] [role="tab"]{color:#b9c8df!important;transition:color .16s ease,text-shadow .16s ease}
body.skk-global-enabled [data-slot="conversation.session.header"] [role="tab"]:hover,body.skk-host-active [data-slot="conversation.session.header"] [role="tab"]:hover{color:#dff8ff!important;text-shadow:0 0 10px rgba(88,217,255,.38)}
body.skk-global-enabled [data-slot="conversation.session.header"] [role="tab"][aria-selected="true"],body.skk-host-active [data-slot="conversation.session.header"] [role="tab"][aria-selected="true"]{color:#9beeff!important;text-shadow:0 0 12px rgba(88,217,255,.55)}
body.skk-global-enabled [data-slot="conversation.session.header"] button,body.skk-host-active [data-slot="conversation.session.header"] button{border-color:rgba(105,214,255,.26)!important;background:rgba(8,14,35,.42)!important;color:#eefaff!important}
@media(prefers-reduced-motion:reduce){.skk-bg,.skk-stars,.skk-character,.skk-character img,.skk-aura,.skk-caret{animation:none!important}}
`
